name: Github Actions Demo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build the docker image
        run: docker build . --file ./Dockerfile --tag inline_scanner_test:latest
        
      - uses: lacework/lw-scanner-action@v1.3.0
        name: Scan container images for vulnerabilities using Lacework
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          IMAGE_NAME: inline_scanner_test:latest
          IMAGE_TAG: latest
          SAVE_RESULTS_IN_LACEWORK: true
          SAVE_BUILD_REPORT: true
          BUILD_REPORT_FILE_NAME: report.html
